version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        REACT_APP_API_URL: 'http://16.16.182.24:5000'
    ports:
      - "85:80"
    networks:
      - mynetwork
    #depends_on:
    #  - backend

  backend:
    container_name: backend
    image: rawlin08/add-2-no:backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://rawlin:rawlin@mongodb:27017/numbers?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rawlin
      - MONGO_INITDB_ROOT_PASSWORD=rawlin
      - MONGO_INITDB_DATABASE=numbers
    networks:
      - mynetwork
    volumes:
      - myvolume:/data/db
    

networks:
  mynetwork:
volumes:
  myvolume:
