version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        REACT_APP_API_URL: 'http://16.16.182.24/:5000'
    
    ports:
      - "85:80"
    networks:
      - mynetwork
    #depends_on:
    #  - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    environment:
      - PORT=5055
    

networks:
  mynetwork:
