name: Add-2-no cicd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test stage
        run: echo This is test stage
  build:
    runs-on: ubuntu:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build stage
        run: echo This is building stage

  


