name: Variables

on:
  workflow_dispatch

env:
  name: rawlin

jobs:
 greetings_job:
  runs-on: ubuntu-latest
  env:
    greetings: Hello
  steps:
    - name: Print Message from variables
      run: echo "$greetings $name",
           echo "Your full name is ${{ vars.MY_NAME }}"
